In [1]:
from mxnet import nd

In [2]:
##########################
# Instantiate two scalars
##########################
x = nd.array([3.0])
y = nd.array([2.0])

##########################
# Add them
##########################
print('x + y = ', x + y)

##########################
# Multiply them
##########################
print('x * y = ', x * y)

##########################
# Divide x by y
##########################
print('x / y = ', x / y)

##########################
# Raise x to the power y.
##########################
print('x ** y = ', nd.power(x,y))

x + y =  
[ 5.]
<NDArray 1 @cpu(0)>
x * y =  
[ 6.]
<NDArray 1 @cpu(0)>
x / y =  
[ 1.5]
<NDArray 1 @cpu(0)>
x ** y =  
[ 9.]
<NDArray 1 @cpu(0)>


In [3]:
x.asscalar()

3.0

In [5]:
u = nd.arange(4)
print('u = ', u)

u =  
[ 0.  1.  2.  3.]
<NDArray 4 @cpu(0)>


In [6]:
u[3]


[ 3.]
<NDArray 1 @cpu(0)>

In [7]:
len(u)

4

In [8]:
u.shape

(4,)

In [9]:
a = 2
x = nd.array([1,2,3])
y = nd.array([10,20,30])
print(a * x)
print(a * x + y)


[ 2.  4.  6.]
<NDArray 3 @cpu(0)>

[ 12.  24.  36.]
<NDArray 3 @cpu(0)>


In [11]:
A = nd.zeros((5,4))
A


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 5x4 @cpu(0)>

In [12]:
x = nd.arange(20)
A = x.reshape((5, 4))
A


[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>

In [13]:
print('A[2, 3] = ', A[2, 3])

A[2, 3] =  
[ 11.]
<NDArray 1 @cpu(0)>


In [14]:
print('row 2', A[2, :])
print('column 3', A[:, 3])

row 2 
[  8.   9.  10.  11.]
<NDArray 4 @cpu(0)>
column 3 
[  3.   7.  11.  15.  19.]
<NDArray 5 @cpu(0)>


In [15]:
A.T


[[  0.   4.   8.  12.  16.]
 [  1.   5.   9.  13.  17.]
 [  2.   6.  10.  14.  18.]
 [  3.   7.  11.  15.  19.]]
<NDArray 4x5 @cpu(0)>

In [16]:
X = nd.arange(24).reshape((2, 3, 4))
print('X.shape =', X.shape)
print('X =', X)

X.shape = (2, 3, 4)
X = 
[[[  0.   1.   2.   3.]
  [  4.   5.   6.   7.]
  [  8.   9.  10.  11.]]

 [[ 12.  13.  14.  15.]
  [ 16.  17.  18.  19.]
  [ 20.  21.  22.  23.]]]
<NDArray 2x3x4 @cpu(0)>


In [17]:
u = nd.array([1, 2, 4, 8])
v = nd.ones_like(u) * 2
print('v =', v)
print('u + v', u + v)
print('u - v', u - v)
print('u * v', u * v)
print('u / v', u / v)

v = 
[ 2.  2.  2.  2.]
<NDArray 4 @cpu(0)>
u + v 
[  3.   4.   6.  10.]
<NDArray 4 @cpu(0)>
u - v 
[-1.  0.  2.  6.]
<NDArray 4 @cpu(0)>
u * v 
[  2.   4.   8.  16.]
<NDArray 4 @cpu(0)>
u / v 
[ 0.5  1.   2.   4. ]
<NDArray 4 @cpu(0)>


In [18]:
B = nd.ones_like(A) * 3
print('B =', B)
print('A + B =', A + B)
print('A * B =', A * B)

B = 
[[ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]]
<NDArray 5x4 @cpu(0)>
A + B = 
[[  3.   4.   5.   6.]
 [  7.   8.   9.  10.]
 [ 11.  12.  13.  14.]
 [ 15.  16.  17.  18.]
 [ 19.  20.  21.  22.]]
<NDArray 5x4 @cpu(0)>
A * B = 
[[  0.   3.   6.   9.]
 [ 12.  15.  18.  21.]
 [ 24.  27.  30.  33.]
 [ 36.  39.  42.  45.]
 [ 48.  51.  54.  57.]]
<NDArray 5x4 @cpu(0)>


In [19]:
a = 2
x = nd.ones(3)
y = nd.zeros(3)
print(x.shape)
print(y.shape)
print((a * x).shape)
print((a * x + y).shape)

(3,)
(3,)
(3,)
(3,)


In [20]:
nd.sum(u)


[ 15.]
<NDArray 1 @cpu(0)>

In [21]:
nd.sum(A)


[ 190.]
<NDArray 1 @cpu(0)>

In [22]:
print(nd.mean(A))
print(nd.sum(A) / A.size)


[ 9.5]
<NDArray 1 @cpu(0)>

[ 9.5]
<NDArray 1 @cpu(0)>


In [23]:
nd.dot(u, v)


[ 30.]
<NDArray 1 @cpu(0)>

In [24]:
nd.sum(u * v)


[ 30.]
<NDArray 1 @cpu(0)>

In [25]:
nd.dot(A, u)


[  34.   94.  154.  214.  274.]
<NDArray 5 @cpu(0)>

In [26]:
A = nd.ones(shape=(3, 4))
B = nd.ones(shape=(4, 5))
nd.dot(A, B)


[[ 4.  4.  4.  4.  4.]
 [ 4.  4.  4.  4.  4.]
 [ 4.  4.  4.  4.  4.]]
<NDArray 3x5 @cpu(0)>

In [27]:
nd.norm(u)


[ 9.21954441]
<NDArray 1 @cpu(0)>

In [28]:
nd.sum(nd.abs(u))


[ 15.]
<NDArray 1 @cpu(0)>