In [1]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)

In [3]:
x = nd.empty((3, 4))
print(x)


[[ -5.03296723e+15   4.55926468e-41   1.60587817e-37   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]]
<NDArray 3x4 @cpu(0)>


In [4]:
x = nd.zeros((3, 5))
x


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
<NDArray 3x5 @cpu(0)>

In [5]:
x = nd.ones((3, 4))
x


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

In [6]:
y = nd.random_normal(0, 1, shape=(3, 4))
y


[[-0.67765152  0.03629481  0.10073948 -0.49024421]
 [ 0.57595438 -0.95017916 -0.3469252   0.03751944]
 [-0.22134334 -0.72984636 -1.80471897 -2.04010558]]
<NDArray 3x4 @cpu(0)>

In [7]:
y.shape

(3, 4)

In [9]:
y.size

12

In [10]:
x + y


[[ 0.32234848  1.03629482  1.10073948  0.50975579]
 [ 1.57595444  0.04982084  0.6530748   1.03751945]
 [ 0.77865666  0.27015364 -0.80471897 -1.04010558]]
<NDArray 3x4 @cpu(0)>

In [11]:
x * y


[[-0.67765152  0.03629481  0.10073948 -0.49024421]
 [ 0.57595438 -0.95017916 -0.3469252   0.03751944]
 [-0.22134334 -0.72984636 -1.80471897 -2.04010558]]
<NDArray 3x4 @cpu(0)>

In [12]:
nd.exp(y)


[[ 0.50780815  1.03696156  1.1059885   0.61247683]
 [ 1.77882743  0.38667175  0.70685822  1.03823221]
 [ 0.80144149  0.48198304  0.16452068  0.13001499]]
<NDArray 3x4 @cpu(0)>

In [13]:
nd.dot(x, y.T)


[[-1.03086138 -0.68363053 -4.79601431]
 [-1.03086138 -0.68363053 -4.79601431]
 [-1.03086138 -0.68363053 -4.79601431]]
<NDArray 3x3 @cpu(0)>

In [14]:
print("id(y)", id(y))
y = y + x
print("id(y)", id(y))

id(y) 139741117376384
id(y) 139744641796416


In [15]:
z = nd.zeros_like(x)
print("id(z)", id(z))
z[:] = x + y
print("id(z)", id(z))

id(z) 139741117378512
id(z) 139741117378512


In [16]:
nd.elemwise_add(x, y, out=z)


[[ 1.32234848  2.03629494  2.10073948  1.50975585]
 [ 2.57595444  1.0498209   1.65307474  2.03751945]
 [ 1.77865672  1.27015364  0.19528103 -0.04010558]]
<NDArray 3x4 @cpu(0)>

In [17]:
print("id(x):", id(x))
x += y
x
print("id(x):", id(x))

id(x): 139741117376440
id(x): 139741117376440


In [18]:
x[1:3]


[[ 2.57595444  1.0498209   1.65307474  2.03751945]
 [ 1.77865672  1.27015364  0.19528103 -0.04010558]]
<NDArray 2x4 @cpu(0)>

In [19]:
x[1, 2] = 9.0
x


[[ 1.32234848  2.03629494  2.10073948  1.50975585]
 [ 2.57595444  1.0498209   9.          2.03751945]
 [ 1.77865672  1.27015364  0.19528103 -0.04010558]]
<NDArray 3x4 @cpu(0)>

In [21]:
x[1: 2, 1: 3]


[[ 1.0498209  9.       ]]
<NDArray 1x2 @cpu(0)>

In [22]:
x[1: 2, 1: 3] = 5.0
x


[[ 1.32234848  2.03629494  2.10073948  1.50975585]
 [ 2.57595444  5.          5.          2.03751945]
 [ 1.77865672  1.27015364  0.19528103 -0.04010558]]
<NDArray 3x4 @cpu(0)>

In [23]:
x = nd.ones(shape=(3, 3))
print("x = ", x)
y = nd.arange(3)
print("y = ", y)
print("x + y = ", x + y)

x =  
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>
y =  
[ 0.  1.  2.]
<NDArray 3 @cpu(0)>
x + y =  
[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
<NDArray 3x3 @cpu(0)>


In [24]:
y = y.reshape((3, 1))
print("y = ", y)
print("x + y = ", x + y)

y =  
[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>
x + y =  
[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]
<NDArray 3x3 @cpu(0)>


In [25]:
a = x.asnumpy()
type(a)

numpy.ndarray

In [26]:
y = nd.array(a)
y


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>

In [27]:
from mxnet import gpu
z = nd.ones(shape=(3, 3), ctx=gpu(0))
z


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @gpu(0)>

In [28]:
x_gpu = x.copyto(gpu(0))
print(x_gpu)


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @gpu(0)>


In [29]:
x_gpu + z


[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]
<NDArray 3x3 @gpu(0)>

In [31]:
print(x_gpu.context)
print(z.context)

gpu(0)
gpu(0)


In [32]:
print('id(z):', id(z))
z = z.copyto(gpu(0))
print('id(z):', id(z))
z = z.as_in_context(gpu(0))
print('id(z):', id(z))
print(z)

id(z): 139741117378288
id(z): 139741117494160
id(z): 139741117494160

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @gpu(0)>
